apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-lucifer
  name: gateway-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-pod
  template:
    metadata:
      labels:
        app: gateway-pod
    spec:
      containers:
        - name: gateway
          image: $image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: harbor-login
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-lucifer
  name: gateway-service
spec:
  selector:
    app: gateway-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30103
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.137.136

#apiVersion: v1
#kind: Service
#metadata:
#  namespace: kube-lucifer
#  name: auth-service
#spec:
#  selector:
#    app: auth-pod
#  ports:
#    - port: 8081
#      targetPort: 8081


